// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupService 提供基于Git的备份功能
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * HandleConfigChange 处理备份配置变更
 */
export function HandleConfigChange(config: models$0.GitBackupConfig | null): $CancellablePromise<void> {
    return $Call.ByID(395287784, config);
}

/**
 * Initialize 初始化备份服务
 */
export function Initialize(): $CancellablePromise<void> {
    return $Call.ByID(1052437974);
}

/**
 * PushToRemote 推送本地更改到远程仓库
 */
export function PushToRemote(): $CancellablePromise<void> {
    return $Call.ByID(262644139);
}

/**
 * Reinitialize 重新初始化备份服务，用于响应配置变更
 */
export function Reinitialize(): $CancellablePromise<void> {
    return $Call.ByID(301562543);
}

/**
 * StartAutoBackup 启动自动备份定时器
 */
export function StartAutoBackup(): $CancellablePromise<void> {
    return $Call.ByID(3035755449);
}

/**
 * StopAutoBackup 停止自动备份
 */
export function StopAutoBackup(): $CancellablePromise<void> {
    return $Call.ByID(2641894021);
}
