// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DatabaseService provides shared database functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * RegisterModel 注册模型与表的映射关系
 */
export function RegisterModel(tableName: string, model: any): $CancellablePromise<void> {
    return $Call.ByID(175397515, tableName, model);
}
