// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocumentService provides document management functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * CreateDocument creates a new document and returns the created document with ID
 */
export function CreateDocument(title: string): $CancellablePromise<models$0.Document | null> {
    return $Call.ByID(3360680842, title).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteDocument marks a document as deleted (default document with ID=1 cannot be deleted)
 */
export function DeleteDocument(id: number): $CancellablePromise<void> {
    return $Call.ByID(412287269, id);
}

/**
 * GetDocumentByID gets a document by ID
 */
export function GetDocumentByID(id: number): $CancellablePromise<models$0.Document | null> {
    return $Call.ByID(3468193232, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListAllDocumentsMeta lists all active (non-deleted) document metadata
 */
export function ListAllDocumentsMeta(): $CancellablePromise<(models$0.Document | null)[]> {
    return $Call.ByID(3073950297).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListDeletedDocumentsMeta lists all deleted document metadata
 */
export function ListDeletedDocumentsMeta(): $CancellablePromise<(models$0.Document | null)[]> {
    return $Call.ByID(490143787).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * LockDocument 锁定文档，防止删除
 */
export function LockDocument(id: number): $CancellablePromise<void> {
    return $Call.ByID(1889494473, id);
}

/**
 * RestoreDocument restores a deleted document
 */
export function RestoreDocument(id: number): $CancellablePromise<void> {
    return $Call.ByID(784200778, id);
}

/**
 * UnlockDocument 解锁文档
 */
export function UnlockDocument(id: number): $CancellablePromise<void> {
    return $Call.ByID(222307930, id);
}

/**
 * UpdateDocumentContent updates the content of a document
 */
export function UpdateDocumentContent(id: number, content: string): $CancellablePromise<void> {
    return $Call.ByID(3251897116, id, content);
}

/**
 * UpdateDocumentTitle updates the title of a document
 */
export function UpdateDocumentTitle(id: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(2045530459, id, title);
}

// Private type creation functions
const $$createType0 = models$0.Document.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
