// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExtensionService 扩展管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetAllExtensions 获取所有扩展配置
 */
export function GetAllExtensions(): $CancellablePromise<models$0.Extension[]> {
    return $Call.ByID(3094292124).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResetAllExtensionsToDefault 重置所有扩展到默认状态
 */
export function ResetAllExtensionsToDefault(): $CancellablePromise<void> {
    return $Call.ByID(270611949);
}

/**
 * ResetExtensionToDefault 重置扩展到默认状态
 */
export function ResetExtensionToDefault(id: models$0.ExtensionID): $CancellablePromise<void> {
    return $Call.ByID(868308101, id);
}

/**
 * UpdateExtensionEnabled 更新扩展启用状态
 */
export function UpdateExtensionEnabled(id: models$0.ExtensionID, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1067300094, id, enabled);
}

/**
 * UpdateExtensionState 更新扩展状态
 */
export function UpdateExtensionState(id: models$0.ExtensionID, enabled: boolean, config: models$0.ExtensionConfig): $CancellablePromise<void> {
    return $Call.ByID(2917946454, id, enabled, config);
}

// Private type creation functions
const $$createType0 = models$0.Extension.createFrom;
const $$createType1 = $Create.Array($$createType0);
