// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThemeService 主题服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetThemeByName 通过名称获取主题覆盖，若不存在则返回 nil
 */
export function GetThemeByName(name: string): $CancellablePromise<models$0.Theme | null> {
    return $Call.ByID(1938954770, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResetTheme 删除指定主题的覆盖配置
 */
export function ResetTheme(name: string): $CancellablePromise<void> {
    return $Call.ByID(1806334457, name);
}

/**
 * UpdateTheme 保存或更新主题覆盖
 */
export function UpdateTheme(name: string, colors: models$0.ThemeColorConfig): $CancellablePromise<void> {
    return $Call.ByID(70189749, name, colors);
}

// Private type creation functions
const $$createType0 = models$0.Theme.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
