// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrayService 系统托盘服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * AutoShowHide 自动显示/隐藏主窗口
 */
export function AutoShowHide(): $CancellablePromise<void> {
    return $Call.ByID(4044219428);
}

/**
 * HandleWindowClose 处理窗口关闭事件
 */
export function HandleWindowClose(): $CancellablePromise<void> {
    return $Call.ByID(1824247204);
}

/**
 * HandleWindowMinimize 处理窗口最小化事件
 */
export function HandleWindowMinimize(): $CancellablePromise<void> {
    return $Call.ByID(178686624);
}

/**
 * MinimizeButtonClicked 处理标题栏最小化按钮点击
 */
export function MinimizeButtonClicked(): $CancellablePromise<void> {
    return $Call.ByID(2477618539);
}

/**
 * ShouldMinimizeToTray 检查是否应该最小化到托盘
 */
export function ShouldMinimizeToTray(): $CancellablePromise<boolean> {
    return $Call.ByID(3403884012);
}

/**
 * ShowWindow 显示主窗口
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(1315913255);
}
