// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 窗口管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * GetOpenWindows 获取所有打开的文档窗口
 */
export function GetOpenWindows(): $CancellablePromise<application$0.Window[]> {
    return $Call.ByID(1464997251).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IsDocumentWindowOpen 检查指定文档的窗口是否已打开
 */
export function IsDocumentWindowOpen(documentID: number): $CancellablePromise<boolean> {
    return $Call.ByID(1735611839, documentID);
}

/**
 * OpenDocumentWindow 为指定文档ID打开新窗口
 */
export function OpenDocumentWindow(documentID: number): $CancellablePromise<void> {
    return $Call.ByID(494716471, documentID);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
