// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    AppConfig,
    AppearanceConfig,
    AuthMethod,
    ConfigMetadata,
    Document,
    EditingConfig,
    Extension,
    ExtensionID,
    GeneralConfig,
    GitBackupConfig,
    GiteaConfig,
    GithubConfig,
    HotkeyCombo,
    KeyBinding,
    KeyBindingCommand,
    LanguageType,
    SystemThemeType,
    TabType,
    Theme,
    ThemeType,
    UpdateSourceType,
    UpdatesConfig
} from "./models.js";

export type {
    ExtensionConfig,
    ThemeColorConfig
} from "./models.js";
